### PR TITLE
Updated Clinvar export XSD to 1.7

### PR DESCRIPTION
**Pull request by ahujameg**
@holtgrewe Please review the changes done for fixing the bug #226 .

### CODE REVIEW

**Comment by holtgrewe** [comment]
The code coverage reporter failure for Python 3.7 can be ignored.

**Review by holtgrewe — CHANGES_REQUESTED** [review]
Looks good to me. Please add a note to the `HISTORY.rst` file, though.

**Comment by holtgrewe** [comment]
OK, please on latest `main` branch and squash commits `git rebase -i main`.

**Comment by ahujameg** [comment]
> OK, please on latest `main` branch and squash commits `git rebase -i main`.

Sorry, I missed seeing this comment. Here I resolved the merge conflict for history.rst file and committed again, will squash all the commits done so far into a single commit now.

**Comment by ahujameg** [comment]
Hi @holtgrewe, Please let me know if anything is pending from my end for this pull request.

**Comment by stolpeo** [comment]
@ahujameg Could you please fetch the latest main branch, do a rebase of your branch and then squash the commits `git rebase -i main`?

**Comment by holtgrewe** [comment]
I put all changes into one commit in #277.

**Pull request closed without merging**
