### PR TITLE
Added settings parameter disable_categories

### PR DESCRIPTION
**Pull request by brand-fabian**
See #147

### CODE REVIEW

**Review by holtgrewe — CHANGES_REQUESTED** [review]
- please use black formatting `make black`
- please try to stick to 52 characters for commit messages, at most ~72/80 or so

**Comment by holtgrewe** [comment]
Also, please include description of change in HISTORY.

**Comment by holtgrewe** [comment]
@brand-fabian you have a different black version apparently, once formatting is fixed this can be merged

**Comment by holtgrewe** [comment]
@brand-fabian is it possible to enable "allow edits by maintainers" for this PR? There a couple of things that I'd like to change before merging.

**Comment by holtgrewe** [comment]
see https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by brand-fabian** [comment]
Edits by maintainers is enabled already. You should be able to change things around.

**Pull request merged**
