### PR TITLE
Add_Transcripts_GnomadAD_constraints_and_clinvar_reports_in_the_export

### PR DESCRIPTION
**Pull request by incardon**
Related-Issue: #568
Projected-Results-Impact: none

### CODE REVIEW

**Review by holtgrewe — COMMENTED** [review]
Note to self: look at the sorting and figure out a solution.

**Review by holtgrewe — COMMENTED** [review]
Lines 37/41:

```
        self.small_vars = SmallVariantFactory.create_batch(3, variant_set=self.variant_set)
```

sorting should go here

**Comment by incardon** [comment]
Is done

**Review by stolpeo — APPROVED** [review]
LGTM

**Comment by stolpeo** [comment]
@incardon @holtgrewe Is it planned to backport the changes?

**Comment by stolpeo** [comment]
@incardon OK, could you then open another branch based on the anthenea branch, somehow transfer this commit to the branch (e.g. cherry-picking), resolve the merge conflicts and do a pull request on our anthenea branch?

**Pull request merged**
