### PR TITLE
Add Transcripts GnomadAD constraints and clinvar reports in the export

### PR DESCRIPTION
**Pull request by incardon**
Closes: #568
Related-Issue: #568
Projected-Results-Impact: none

### CODE REVIEW

**Comment by incardon** [comment]
I do not know if something has changed, but I have problem to see why codacy complain

**Comment by holtgrewe** [comment]
We can ignore codacy complains, I believe.

**Comment by incardon** [comment]
An error occurred during this step. Please, [retry your analysis]( or [contact support.]

Deltas

An error occurred during this step. Please, [retry your analysis] or [contact support.]

**Comment by incardon** [comment]
Perfect Thanks

**Review by stolpeo — APPROVED** [review]
LGTM

**Pull request merged**
